import type { Metadata } from "next";
import "./globals.css";
import { Hepta_Slab } from "next/font/google";

const heptaSlab = Hepta_Slab({
	preload: true,
	subsets: ["latin", "latin-ext"],
	weight: "400",
	variable: "--f-hepta-slab",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${heptaSlab.className} antialiased`}>{children}</body>
		</html>
	);
}
